"""AccountOrm: добавил баланс всегда положительный, и name уникальный для в пределах одного user

Revision ID: 0d6103e50d24
Revises: dd07234cdc8f
Create Date: 2025-09-23 15:51:05.762395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6103e50d24'
down_revision: Union[str, Sequence[str], None] = 'dd07234cdc8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_account_user_name', 'accounts', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_account_user_name', 'accounts', type_='unique')
    # ### end Alembic commands ###
