"""RefreshTokenOrm: поменял настройку entry_updated_at

Revision ID: 205db5d5b24f
Revises: c1d35f8117fb
Create Date: 2025-09-21 13:30:11.021425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205db5d5b24f'
down_revision: Union[str, Sequence[str], None] = 'c1d35f8117fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
