"""AccountOrm: убран с deleted_at nullable False

Revision ID: 3886cb352091
Revises: beef7e547d41
Create Date: 2025-10-02 17:04:49.576605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3886cb352091'
down_revision: Union[str, Sequence[str], None] = 'beef7e547d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('uq_account_user_name'), 'accounts', type_='unique')
    op.drop_constraint(op.f('uq_user_category_title'), 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_category_title'), 'categories', ['user_id', 'title'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_account_user_name'), 'accounts', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('accounts', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
