"""AccountOrm: проиндексировал name, так как по name удаляется

Revision ID: 4cf4d7228e92
Revises: 0d6103e50d24
Create Date: 2025-09-23 15:59:50.953883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf4d7228e92'
down_revision: Union[str, Sequence[str], None] = '0d6103e50d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    # ### end Alembic commands ###
