"""empty message

Revision ID: 7c6a0a7b0808
Revises: a12d28068a8d
Create Date: 2025-10-28 14:25:41.459417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6a0a7b0808'
down_revision: Union[str, Sequence[str], None] = 'a12d28068a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('balance_after', sa.Numeric(precision=25, scale=2), server_default='0', nullable=False))
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=25, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'rate',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=25, scale=2),
               existing_nullable=True)
    op.alter_column('transactions', 'commission',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=25, scale=2),
               existing_nullable=True)
    op.add_column('users', sa.Column('utc_offset', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'utc_offset')
    op.alter_column('transactions', 'commission',
               existing_type=sa.Numeric(precision=25, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('transactions', 'rate',
               existing_type=sa.Numeric(precision=25, scale=2),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=25, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('transactions', 'balance_after')
    # ### end Alembic commands ###
