"""empty message

Revision ID: a12d28068a8d
Revises: 0ca6132046d6
Create Date: 2025-10-05 15:18:41.880219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a12d28068a8d'
down_revision: Union[str, Sequence[str], None] = '0ca6132046d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('transactions', sa.Column('commission', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'commission')
    op.drop_column('transactions', 'rate')
    # ### end Alembic commands ###
