"""AccountOrm: сделан enum для валюты. UserOrm: index убран с verification_token. Создан CategoryOrm

Revision ID: debb5f6c9797
Revises: 1053a843b3b0
Create Date: 2025-09-30 17:17:18.398775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'debb5f6c9797'
down_revision: Union[str, Sequence[str], None] = '1053a843b3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category_type', sa.Enum('INCOME', 'EXPENSE', name='category_type_enum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title', name='uq_user_category_title')
    )
    op.create_index(op.f('ix_categories_category_type'), 'categories', ['category_type'], unique=False)
    op.create_index(op.f('ix_categories_title'), 'categories', ['title'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.alter_column('accounts', 'currency',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RUB', 'INR', 'IRR', 'BRL', 'UZC', 'TRY', 'BYN', 'KZT', 'UAH', 'USD', 'EUR', 'JPY', 'GBP', 'CNY', name='currency_enum'),
               existing_nullable=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.alter_column('accounts', 'currency',
               existing_type=sa.Enum('RUB', 'INR', 'IRR', 'BRL', 'UZC', 'TRY', 'BYN', 'KZT', 'UAH', 'USD', 'EUR', 'JPY', 'GBP', 'CNY', name='currency_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_title'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_type'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
