"""UserOrm: verification_token проиндексирован

Revision ID: e7e65bbb6b73
Revises: ad5879ac681a
Create Date: 2025-09-24 22:02:08.526910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e65bbb6b73'
down_revision: Union[str, Sequence[str], None] = 'ad5879ac681a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_verification_token_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.create_unique_constraint(op.f('users_verification_token_key'), 'users', ['verification_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
